--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_conversation_documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_conversation_documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    ai_conversation_id bigint NOT NULL,
    document_version_id bigint NOT NULL
);


--
-- Name: ai_conversation_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_conversation_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_conversation_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_conversations (
    id bigint NOT NULL,
    conversation_type character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    status character varying(20) NOT NULL,
    user_id bigint,
    CONSTRAINT ai_conversations_conversation_type_check CHECK (((conversation_type)::text = ANY ((ARRAY['EMAIL_GENERATION'::character varying, 'REPORT_GENERATION'::character varying, 'MEETING_MINUTES_GENERATION'::character varying, 'SUMMARY_GENERATION'::character varying, 'FORM_GENERATION'::character varying, 'DOCUMENT_QA'::character varying, 'SEMANTIC_SEARCH'::character varying, 'DOCUMENT_INDEXING'::character varying])::text[]))),
    CONSTRAINT ai_conversations_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: ai_conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_message_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_message_sources (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    score double precision,
    ai_message_id bigint NOT NULL,
    document_chunk_id bigint NOT NULL,
    similarity_score double precision,
    chunk_id bigint NOT NULL,
    document_version_id bigint NOT NULL
);


--
-- Name: ai_message_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_message_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_message_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_messages (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    role character varying(20) NOT NULL,
    ai_conversation_id bigint NOT NULL,
    token_count integer,
    CONSTRAINT ai_messages_role_check CHECK (((role)::text = ANY (ARRAY[('USER'::character varying)::text, ('ASSISTANT'::character varying)::text, ('SYSTEM'::character varying)::text])))
);


--
-- Name: ai_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_usage_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_usage_logs (
    id bigint NOT NULL,
    conversation_type smallint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    error_message text,
    estimated_cost numeric(12,6) NOT NULL,
    input_tokens integer NOT NULL,
    model character varying(100) NOT NULL,
    output_tokens integer NOT NULL,
    status character varying(20) NOT NULL,
    total_tokens integer NOT NULL,
    ai_conversation_id bigint,
    ai_message_id bigint,
    generation_id bigint,
    department_id bigint,
    user_id bigint,
    CONSTRAINT ai_usage_logs_conversation_type_check CHECK (((conversation_type >= 0) AND (conversation_type <= 7))),
    CONSTRAINT ai_usage_logs_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: ai_usage_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_usage_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_usage_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversation_memories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversation_memories (
    id bigint NOT NULL,
    context_character_count integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    pending_context text,
    summarized_context text,
    updated_at timestamp(6) without time zone NOT NULL,
    ai_conversation_id bigint NOT NULL
);


--
-- Name: conversation_memories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversation_memories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversation_memories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description text,
    name character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    manager_id bigint
);


--
-- Name: departments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.departments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_accesses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_accesses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    document_id bigint NOT NULL,
    granted_by bigint,
    user_id bigint NOT NULL
);


--
-- Name: document_accesses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_accesses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_accesses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_chunks (
    id bigint NOT NULL,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_char integer,
    page_number integer,
    start_char integer,
    token_count integer,
    document_version_id bigint NOT NULL
);


--
-- Name: document_chunks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_chunks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_texts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_texts (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    extraction_method character varying(50) NOT NULL,
    language character varying(50),
    updated_at timestamp(6) without time zone NOT NULL,
    document_version_id bigint NOT NULL,
    CONSTRAINT document_texts_extraction_method_check CHECK (((extraction_method)::text = ANY ((ARRAY['DIRECT_TEXT'::character varying, 'OCR'::character varying, 'MANUAL'::character varying, 'AI_ENHANCED'::character varying])::text[])))
);


--
-- Name: document_texts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_texts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_texts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_versions (
    id bigint NOT NULL,
    change_note text,
    created_at timestamp(6) without time zone NOT NULL,
    error_message text,
    status character varying(255) NOT NULL,
    version_number integer NOT NULL,
    document_id bigint NOT NULL,
    file_id bigint NOT NULL,
    processing_step character varying(255),
    CONSTRAINT document_versions_processing_step_check CHECK (((processing_step)::text = ANY ((ARRAY['TEXT_EXTRACTING'::character varying, 'CHUNKING'::character varying, 'EMBEDDING'::character varying])::text[]))),
    CONSTRAINT document_versions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'READY'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: document_versions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.document_versions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.document_versions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    description text,
    document_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(500) NOT NULL,
    updated_at timestamp(6) without time zone,
    current_version_id bigint,
    folder_id bigint,
    deleted_by bigint,
    department_id bigint,
    owner_id bigint,
    CONSTRAINT documents_document_type_check CHECK (((document_type)::text = ANY ((ARRAY['EMAIL_TEMPLATE'::character varying, 'REPORT'::character varying, 'MEETING_MINUTES'::character varying, 'FORM'::character varying, 'CONTRACT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT documents_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.files (
    id bigint NOT NULL,
    bucket_name character varying(255),
    checksum character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    extension character varying(50),
    file_size bigint,
    mime_type character varying(255),
    object_key character varying(1000) NOT NULL,
    original_filename character varying(500) NOT NULL,
    storage_provider character varying(50) NOT NULL,
    stored_filename character varying(500) NOT NULL,
    preview_file_id bigint
);


--
-- Name: files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: folders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.folders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    parent_id bigint,
    deleted_by bigint,
    department_id bigint,
    owner_id bigint,
    CONSTRAINT folders_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: folders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.folders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.folders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: generated_content; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generated_content (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    generated_type character varying(50) NOT NULL,
    title character varying(500) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    CONSTRAINT generated_content_generated_type_check CHECK (((generated_type)::text = ANY (ARRAY[('EMAIL'::character varying)::text, ('REPORT'::character varying)::text, ('MEETING_MINUTES'::character varying)::text, ('SUMMARY'::character varying)::text, ('FORM'::character varying)::text])))
);


--
-- Name: generated_content_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.generated_content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generated_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: generation_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generation_runs (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) without time zone,
    error_message text,
    generated_type character varying(255) NOT NULL,
    input_data json,
    status character varying(255) NOT NULL,
    title character varying(500),
    updated_at timestamp(6) without time zone NOT NULL,
    user_prompt text,
    ai_conversation_id bigint NOT NULL,
    generated_content_id bigint,
    CONSTRAINT generation_runs_generated_type_check CHECK (((generated_type)::text = ANY ((ARRAY['EMAIL'::character varying, 'REPORT'::character varying, 'MEETING_MINUTES'::character varying, 'SUMMARY'::character varying, 'FORM'::character varying])::text[]))),
    CONSTRAINT generation_runs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: generation_runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.generation_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generation_runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: generations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generations (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted boolean NOT NULL,
    deleted_at timestamp(6) without time zone,
    error_message text,
    generated_type character varying(255) NOT NULL,
    input_data jsonb,
    status character varying(255) NOT NULL,
    title character varying(500),
    updated_at timestamp(6) without time zone NOT NULL,
    user_prompt text,
    ai_conversation_id bigint NOT NULL,
    generated_content_id bigint,
    CONSTRAINT generations_generated_type_check CHECK (((generated_type)::text = ANY ((ARRAY['EMAIL'::character varying, 'REPORT'::character varying, 'MEETING_MINUTES'::character varying, 'SUMMARY'::character varying, 'FORM'::character varying])::text[]))),
    CONSTRAINT generations_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: generations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.generations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id uuid NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    jti character varying(255) NOT NULL,
    revoked boolean NOT NULL,
    token_hash character varying(512) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    id bigint NOT NULL,
    permission character varying(50) NOT NULL,
    role character varying(30) NOT NULL,
    CONSTRAINT role_permissions_permission_check CHECK (((permission)::text = ANY ((ARRAY['USER_READ'::character varying, 'USER_CREATE'::character varying, 'USER_UPDATE'::character varying, 'USER_DELETE'::character varying, 'USER_ENABLE'::character varying, 'USER_DISABLE'::character varying, 'USER_ASSIGN_ROLE'::character varying, 'USER_CHANGE_DEPARTMENT'::character varying, 'DEPARTMENT_READ'::character varying, 'DEPARTMENT_CREATE'::character varying, 'DEPARTMENT_UPDATE'::character varying, 'DEPARTMENT_DELETE'::character varying, 'DEPARTMENT_MANAGE_MEMBERS'::character varying, 'DOCUMENT_READ'::character varying, 'DOCUMENT_CREATE'::character varying, 'DOCUMENT_UPDATE'::character varying, 'DOCUMENT_DELETE'::character varying, 'DOCUMENT_DOWNLOAD'::character varying, 'DOCUMENT_MANAGE_ACCESS'::character varying, 'FOLDER_READ'::character varying, 'FOLDER_CREATE'::character varying, 'FOLDER_UPDATE'::character varying, 'FOLDER_DELETE'::character varying, 'AI_CHAT'::character varying, 'AI_DOCUMENT_QA'::character varying, 'AI_DOCUMENT_SUMMARY'::character varying, 'AI_DOCUMENT_GENERATION'::character varying, 'AI_SEMANTIC_SEARCH'::character varying, 'CONVERSATION_CREATE'::character varying, 'CONVERSATION_READ'::character varying, 'CONVERSATION_UPDATE'::character varying, 'CONVERSATION_DELETE'::character varying, 'AI_USAGE_READ_SELF'::character varying, 'AI_USAGE_READ_DEPARTMENT'::character varying, 'AI_USAGE_READ_ALL'::character varying])::text[]))),
    CONSTRAINT role_permissions_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'EMPLOYEE'::character varying, 'SUPERVISOR'::character varying])::text[])))
);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    username character varying(100) NOT NULL,
    department_id bigint,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'EMPLOYEE'::character varying, 'SUPERVISOR'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_conversation_documents ai_conversation_documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_conversation_documents
    ADD CONSTRAINT ai_conversation_documents_pkey PRIMARY KEY (id);


--
-- Name: ai_conversations ai_conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_conversations
    ADD CONSTRAINT ai_conversations_pkey PRIMARY KEY (id);


--
-- Name: ai_message_sources ai_message_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_message_sources
    ADD CONSTRAINT ai_message_sources_pkey PRIMARY KEY (id);


--
-- Name: ai_messages ai_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT ai_messages_pkey PRIMARY KEY (id);


--
-- Name: ai_usage_logs ai_usage_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_usage_logs
    ADD CONSTRAINT ai_usage_logs_pkey PRIMARY KEY (id);


--
-- Name: conversation_memories conversation_memories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_memories
    ADD CONSTRAINT conversation_memories_pkey PRIMARY KEY (id);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: document_accesses document_accesses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_accesses
    ADD CONSTRAINT document_accesses_pkey PRIMARY KEY (id);


--
-- Name: document_chunks document_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (id);


--
-- Name: document_texts document_texts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_texts
    ADD CONSTRAINT document_texts_pkey PRIMARY KEY (id);


--
-- Name: document_versions document_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT document_versions_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: files files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT files_pkey PRIMARY KEY (id);


--
-- Name: folders folders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT folders_pkey PRIMARY KEY (id);


--
-- Name: generated_content generated_content_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generated_content
    ADD CONSTRAINT generated_content_pkey PRIMARY KEY (id);


--
-- Name: generation_runs generation_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation_runs
    ADD CONSTRAINT generation_runs_pkey PRIMARY KEY (id);


--
-- Name: generations generations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT generations_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens uk18kw8ppjw4gmmgdns9ecyg17b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk18kw8ppjw4gmmgdns9ecyg17b UNIQUE (jti);


--
-- Name: documents uk50lxqck84m4dsbfa4kds7u1ml; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT uk50lxqck84m4dsbfa4kds7u1ml UNIQUE (current_version_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: ai_conversation_documents uk_ai_conv_doc_conversation_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_conversation_documents
    ADD CONSTRAINT uk_ai_conv_doc_conversation_version UNIQUE (ai_conversation_id, document_version_id);


--
-- Name: ai_conversation_documents uk_ai_conversation_document_conversation_version; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_conversation_documents
    ADD CONSTRAINT uk_ai_conversation_document_conversation_version UNIQUE (ai_conversation_id, document_version_id);


--
-- Name: document_accesses uk_document_access_document_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_accesses
    ADD CONSTRAINT uk_document_access_document_user UNIQUE (document_id, user_id);


--
-- Name: document_chunks uk_document_chunks_version_chunk_index; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT uk_document_chunks_version_chunk_index UNIQUE (document_version_id, chunk_index);


--
-- Name: role_permissions uk_role_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT uk_role_permission UNIQUE (role, permission);


--
-- Name: conversation_memories ukavc48x4uyo0uvd3c3wbihmhyp; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_memories
    ADD CONSTRAINT ukavc48x4uyo0uvd3c3wbihmhyp UNIQUE (ai_conversation_id);


--
-- Name: document_versions ukei968s1e4986g2skkutsuo910; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT ukei968s1e4986g2skkutsuo910 UNIQUE (document_id, version_number);


--
-- Name: departments ukj6cwks7xecs5jov19ro8ge3qk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT ukj6cwks7xecs5jov19ro8ge3qk UNIQUE (name);


--
-- Name: document_texts ukji0bysod39ikxw5qqe14phk8; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_texts
    ADD CONSTRAINT ukji0bysod39ikxw5qqe14phk8 UNIQUE (document_version_id);


--
-- Name: generations ukmk34ww3f2min1a25s492mdumb; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT ukmk34ww3f2min1a25s492mdumb UNIQUE (generated_content_id);


--
-- Name: refresh_tokens uko2mlirhldriil2y7krapq4frt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uko2mlirhldriil2y7krapq4frt UNIQUE (token_hash);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: document_versions uktl7egfx1tjwdb3tkrbsxckdpo; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT uktl7egfx1tjwdb3tkrbsxckdpo UNIQUE (file_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_ai_conv_doc_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conv_doc_conversation_id ON public.ai_conversation_documents USING btree (ai_conversation_id);


--
-- Name: idx_ai_conv_doc_version_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conv_doc_version_id ON public.ai_conversation_documents USING btree (document_version_id);


--
-- Name: idx_ai_conversation_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conversation_created_at ON public.ai_conversations USING btree (created_at);


--
-- Name: idx_ai_conversation_document_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conversation_document_conversation_id ON public.ai_conversation_documents USING btree (ai_conversation_id);


--
-- Name: idx_ai_conversation_document_version_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conversation_document_version_id ON public.ai_conversation_documents USING btree (document_version_id);


--
-- Name: idx_ai_conversation_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conversation_status ON public.ai_conversations USING btree (status);


--
-- Name: idx_ai_conversation_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conversation_type ON public.ai_conversations USING btree (conversation_type);


--
-- Name: idx_ai_conversation_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_conversation_user_id ON public.ai_conversations USING btree (user_id);


--
-- Name: idx_ai_message_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_message_conversation_id ON public.ai_messages USING btree (ai_conversation_id);


--
-- Name: idx_ai_message_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_message_created_at ON public.ai_messages USING btree (created_at);


--
-- Name: idx_ai_message_source_chunk_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_message_source_chunk_id ON public.ai_message_sources USING btree (document_chunk_id);


--
-- Name: idx_ai_message_source_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_message_source_message_id ON public.ai_message_sources USING btree (ai_message_id);


--
-- Name: idx_ai_message_sources_document_version_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_message_sources_document_version_id ON public.ai_message_sources USING btree (document_version_id);


--
-- Name: idx_ai_messages_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_messages_role ON public.ai_messages USING btree (role);


--
-- Name: idx_ai_msg_source_chunk_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_msg_source_chunk_id ON public.ai_message_sources USING btree (document_chunk_id);


--
-- Name: idx_ai_msg_source_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_msg_source_message_id ON public.ai_message_sources USING btree (ai_message_id);


--
-- Name: idx_ai_usage_conversation_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_usage_conversation_type ON public.ai_usage_logs USING btree (conversation_type);


--
-- Name: idx_ai_usage_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_usage_created_at ON public.ai_usage_logs USING btree (created_at);


--
-- Name: idx_ai_usage_department_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_usage_department_id ON public.ai_usage_logs USING btree (department_id);


--
-- Name: idx_ai_usage_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_usage_status ON public.ai_usage_logs USING btree (status);


--
-- Name: idx_ai_usage_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_usage_user_id ON public.ai_usage_logs USING btree (user_id);


--
-- Name: idx_department_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_department_created_at ON public.departments USING btree (created_at);


--
-- Name: idx_department_manager_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_department_manager_id ON public.departments USING btree (manager_id);


--
-- Name: idx_document_access_document_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_access_document_id ON public.document_accesses USING btree (document_id);


--
-- Name: idx_document_access_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_access_user_id ON public.document_accesses USING btree (user_id);


--
-- Name: idx_document_chunks_version_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_chunks_version_id ON public.document_chunks USING btree (document_version_id);


--
-- Name: idx_document_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_created_at ON public.documents USING btree (created_at);


--
-- Name: idx_document_current_version_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_current_version_id ON public.documents USING btree (current_version_id);


--
-- Name: idx_document_department_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_department_id ON public.documents USING btree (department_id);


--
-- Name: idx_document_folder_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_folder_id ON public.documents USING btree (folder_id);


--
-- Name: idx_document_owner_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_owner_id ON public.documents USING btree (owner_id);


--
-- Name: idx_document_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_status ON public.documents USING btree (status);


--
-- Name: idx_document_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_type ON public.documents USING btree (document_type);


--
-- Name: idx_document_version_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_version_created_at ON public.document_versions USING btree (created_at);


--
-- Name: idx_document_version_document_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_version_document_id ON public.document_versions USING btree (document_id);


--
-- Name: idx_document_version_file_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_version_file_id ON public.document_versions USING btree (file_id);


--
-- Name: idx_document_version_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_document_version_status ON public.document_versions USING btree (status);


--
-- Name: idx_file_checksum; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_file_checksum ON public.files USING btree (checksum);


--
-- Name: idx_file_object_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_file_object_key ON public.files USING btree (object_key);


--
-- Name: idx_folder_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_folder_created_at ON public.folders USING btree (created_at);


--
-- Name: idx_folder_department_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_folder_department_id ON public.folders USING btree (department_id);


--
-- Name: idx_folder_owner_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_folder_owner_id ON public.folders USING btree (owner_id);


--
-- Name: idx_folder_parent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_folder_parent_id ON public.folders USING btree (parent_id);


--
-- Name: idx_folder_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_folder_status ON public.folders USING btree (status);


--
-- Name: idx_generated_content_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generated_content_type ON public.generated_content USING btree (generated_type);


--
-- Name: idx_generation_content_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generation_content_id ON public.generations USING btree (generated_content_id);


--
-- Name: idx_generation_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generation_conversation_id ON public.generations USING btree (ai_conversation_id);


--
-- Name: idx_generation_run_content_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generation_run_content_id ON public.generation_runs USING btree (generated_content_id);


--
-- Name: idx_generation_run_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generation_run_conversation_id ON public.generation_runs USING btree (ai_conversation_id);


--
-- Name: idx_generation_run_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generation_run_status ON public.generation_runs USING btree (status);


--
-- Name: idx_generation_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_generation_status ON public.generations USING btree (status);


--
-- Name: idx_refresh_token_jti; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_jti ON public.refresh_tokens USING btree (jti);


--
-- Name: idx_refresh_token_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_refresh_token_user_id ON public.refresh_tokens USING btree (user_id);


--
-- Name: idx_role_permission_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_role_permission_role ON public.role_permissions USING btree (role);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: ai_message_sources fk1o69ysl8aje6udxql21i50qfa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_message_sources
    ADD CONSTRAINT fk1o69ysl8aje6udxql21i50qfa FOREIGN KEY (document_chunk_id) REFERENCES public.document_chunks(id);


--
-- Name: ai_conversations fk1uq0peq5ttjvbxb52g4a4pmhx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_conversations
    ADD CONSTRAINT fk1uq0peq5ttjvbxb52g4a4pmhx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: ai_messages fk2scyffcrgl5p7wkvhd05u12md; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT fk2scyffcrgl5p7wkvhd05u12md FOREIGN KEY (ai_conversation_id) REFERENCES public.ai_conversations(id);


--
-- Name: generation_runs fk3vsqochn60lfhig9cgpsai2fb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation_runs
    ADD CONSTRAINT fk3vsqochn60lfhig9cgpsai2fb FOREIGN KEY (generated_content_id) REFERENCES public.generated_content(id);


--
-- Name: conversation_memories fk4gpw8angmi8eq9m0p63a7dxg1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_memories
    ADD CONSTRAINT fk4gpw8angmi8eq9m0p63a7dxg1 FOREIGN KEY (ai_conversation_id) REFERENCES public.ai_conversations(id);


--
-- Name: folders fk5b5p96ewk9msg1omqhl0vttop; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT fk5b5p96ewk9msg1omqhl0vttop FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: folders fk5vsgnw90c527oeuxmn5dskxi3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT fk5vsgnw90c527oeuxmn5dskxi3 FOREIGN KEY (deleted_by) REFERENCES public.users(id);


--
-- Name: files fk6au64bxymtl440tumic5x51nh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.files
    ADD CONSTRAINT fk6au64bxymtl440tumic5x51nh FOREIGN KEY (preview_file_id) REFERENCES public.files(id);


--
-- Name: ai_conversation_documents fk8jbgckb2xql7ld63buuqe4xn1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_conversation_documents
    ADD CONSTRAINT fk8jbgckb2xql7ld63buuqe4xn1 FOREIGN KEY (document_version_id) REFERENCES public.document_versions(id);


--
-- Name: documents fk9nqrsj4vj0hi1k55nlwv33cr0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk9nqrsj4vj0hi1k55nlwv33cr0 FOREIGN KEY (folder_id) REFERENCES public.folders(id);


--
-- Name: documents fkb5jhh8odm12um5ehhgn9xk6jv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkb5jhh8odm12um5ehhgn9xk6jv FOREIGN KEY (current_version_id) REFERENCES public.document_versions(id);


--
-- Name: ai_usage_logs fkb8kfyym4qh6hf300dxiglxy99; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_usage_logs
    ADD CONSTRAINT fkb8kfyym4qh6hf300dxiglxy99 FOREIGN KEY (ai_conversation_id) REFERENCES public.ai_conversations(id);


--
-- Name: ai_conversation_documents fkc54snsxvdg9a2teofmc9ullbw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_conversation_documents
    ADD CONSTRAINT fkc54snsxvdg9a2teofmc9ullbw FOREIGN KEY (ai_conversation_id) REFERENCES public.ai_conversations(id);


--
-- Name: document_accesses fkfe56851lmjtjrnriqr9spukcr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_accesses
    ADD CONSTRAINT fkfe56851lmjtjrnriqr9spukcr FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: document_versions fkh0jj7efd0fpr0l4nmvae47kih; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT fkh0jj7efd0fpr0l4nmvae47kih FOREIGN KEY (file_id) REFERENCES public.files(id);


--
-- Name: generations fkh31rgfanwqpe4hugnj4ip41t7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT fkh31rgfanwqpe4hugnj4ip41t7 FOREIGN KEY (ai_conversation_id) REFERENCES public.ai_conversations(id);


--
-- Name: documents fkhtlwf3e8ua3jcfko65antrpcy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkhtlwf3e8ua3jcfko65antrpcy FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: document_texts fki201ymp2s2runarkeo1cn0d5d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_texts
    ADD CONSTRAINT fki201ymp2s2runarkeo1cn0d5d FOREIGN KEY (document_version_id) REFERENCES public.document_versions(id);


--
-- Name: document_versions fki6p7dgv96b8s8ivf84hqo9pt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_versions
    ADD CONSTRAINT fki6p7dgv96b8s8ivf84hqo9pt FOREIGN KEY (document_id) REFERENCES public.documents(id);


--
-- Name: departments fkia71ute4clfbt6u2auufvw1bv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT fkia71ute4clfbt6u2auufvw1bv FOREIGN KEY (manager_id) REFERENCES public.users(id);


--
-- Name: ai_message_sources fkjbkfoi0jpkplpm620v28266be; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_message_sources
    ADD CONSTRAINT fkjbkfoi0jpkplpm620v28266be FOREIGN KEY (ai_message_id) REFERENCES public.ai_messages(id);


--
-- Name: generation_runs fkjyl6turdo6mnrxf9yhc2s8mii; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation_runs
    ADD CONSTRAINT fkjyl6turdo6mnrxf9yhc2s8mii FOREIGN KEY (ai_conversation_id) REFERENCES public.ai_conversations(id);


--
-- Name: generations fkktr1su9k8q0n12j4fbtt7nnci; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT fkktr1su9k8q0n12j4fbtt7nnci FOREIGN KEY (generated_content_id) REFERENCES public.generated_content(id);


--
-- Name: document_chunks fkllwtvievy4flyjdrocsovcwdj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT fkllwtvievy4flyjdrocsovcwdj FOREIGN KEY (document_version_id) REFERENCES public.document_versions(id);


--
-- Name: ai_usage_logs fkn1ukua4783iel0jw042nelv3p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_usage_logs
    ADD CONSTRAINT fkn1ukua4783iel0jw042nelv3p FOREIGN KEY (ai_message_id) REFERENCES public.ai_messages(id);


--
-- Name: folders fknlksebbyh5l3c1riw9f2im90a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT fknlksebbyh5l3c1riw9f2im90a FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: documents fkoduxo6gl9tkyx39jo5kue60bq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkoduxo6gl9tkyx39jo5kue60bq FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: folders fkqcp836dgme9195j0wy9v3b6o3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT fkqcp836dgme9195j0wy9v3b6o3 FOREIGN KEY (parent_id) REFERENCES public.folders(id);


--
-- Name: document_accesses fks8btc4xaau4imnpp8gb6b2m3l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_accesses
    ADD CONSTRAINT fks8btc4xaau4imnpp8gb6b2m3l FOREIGN KEY (document_id) REFERENCES public.documents(id);


--
-- Name: users fksbg59w8q63i0oo53rlgvlcnjq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fksbg59w8q63i0oo53rlgvlcnjq FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: document_accesses fkssnccovbxgc3abuqujih0jids; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_accesses
    ADD CONSTRAINT fkssnccovbxgc3abuqujih0jids FOREIGN KEY (granted_by) REFERENCES public.users(id);


--
-- Name: documents fkstx96y4m8xhsd5odedm6w77jy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkstx96y4m8xhsd5odedm6w77jy FOREIGN KEY (deleted_by) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--


